### ISSUE TITLE
Exportar tabela com valor de mercado.

### ISSUE THREAD

**Issue by vitorjoaofg** [StefanYohansson/fipe-extractor#2]

**Comment by jozephbrasil** [comment]
Funciona pra caminhões e motos. O JSON está sendo criado... Mas Carros, não.

# node get-fipe.js 
Tabela Fipe exportada com sucesso.
Tabela Fipe exportada com sucesso.
(node:3100) UnhandledPromiseRejectionWarning: TypeError: r.reduce is not a function
    at mestre_grilo.map (/var/www/html/fipe-extractor/get-fipe.js:187:21)
    at Array.map (<anonymous>)
    at Promise.all.then (/var/www/html/fipe-extractor/get-fipe.js:186:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:3100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Alguem está recebendo esse erro?

**Comment by StefanYohansson** [comment]
Olá, vou verificar... qual a versão do node que está usando?

**Comment by jozephbrasil** [comment]
# node -v
v8.15.1

**Comment by jozephbrasil** [comment]
Não consegui corrigir o problema ainda. Será que alguém tem alguma noção do que esteja causando o erro?

**Comment by jozephbrasil** [comment]
@StefanYohansson Qual versão do node você roda com ele funcionando normalmente? Sua versão é a mesma?

**Comment by allanc85** [comment]
> Não consegui corrigir o problema ainda. Será que alguém tem alguma noção do que esteja causando o erro?

@jozephbrasil , acredito que o site da FIPE esteja bloqueando o acesso após algumas execuções (em um período curto de tempo), pois a exportação é executada com sucesso, quando executado apenas para carros.
Tentei fazer várias requisições em python, e após algumas chamadas, recebo um erro na chamada ao serviço deles.
